version: "3.8"

services:
  app:
    container_name: uj-ebiznes-frontend-dev
    image: uj-ebiznes-frontend-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
